insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 1,'Eula','Lane','eula.lane@jigrormo.ye','(762) 526-5961','1953-12-01','Insurance Clerk','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 2,'Barry','Rodriquez','barry.rodriquez@zun.mm','(267) 955-5124','2012-12-01','Mortarman','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 3,'Eugenia','Selvi','eugenia.selvi@capfad.vn','(680) 368-2192','1972-11-16','Beer Coil Cleaner','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 4,'Alejandro','Miles','alejandro.miles@dec.bn','(281) 301-2039','2013-01-03','Scale Attendant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 5,'Cora','Tesi','cora.tesi@bivo.yt','(600) 616-7955','1971-03-03','Clinical Audiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 6,'Marguerite','Ishii','marguerite.ishii@judbilo.gn','(882) 813-1374','1936-11-28','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 7,'Mildred','Jacobs','mildred.jacobs@joraf.wf','(642) 665-1763','1966-07-03','Business Unit Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 8,'Gene','Goodman','gene.goodman@kem.tl','(383) 458-2132','2009-05-13','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 9,'Lettie','Bennett','lettie.bennett@odeter.bb','(769) 335-6771','1958-07-18','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 10,'Mabel','Leach','mabel.leach@lisohuje.vi','(803) 586-8035','1945-06-24','Food Chemist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 11,'Jordan','Miccinesi','jordan.miccinesi@duod.gy','(531) 919-2280','1981-08-05','Signals Intelligence/Electronic Warfare Chief','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 12,'Marie','Parkes','marie.parkes@nowufpus.ph','(814) 667-8937','1942-06-06','Language Pathologist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 13,'Rose','Gray','rose.gray@kagu.hr','(713) 311-8766','1957-06-05','Wildlife Officer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 14,'Garrett','Stokes','garrett.stokes@fef.bg','(381) 421-2371','2008-03-16','Bindery Machine Operator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 15,'Barbara','Matthieu','barbara.matthieu@derwogi.jm','(940) 463-7299','1929-03-12','Instructional Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 16,'Jean','Rhodes','jean.rhodes@wehovuce.gu','(777) 435-9570','1948-08-19','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 17,'Jack','Romoli','jack.romoli@zamum.bw','(517) 393-9630','1974-06-15','Mortician Investigator','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 18,'Pearl','Holden','pearl.holden@dunebuh.cr','(711) 904-3669','1948-10-10','Rod Buster Helper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 19,'Belle','Montero','belle.montero@repiwid.si','(935) 404-4792','1931-11-03','Classroom Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 20,'Olive','Molina','olive.molina@razuppa.ga','(935) 267-8492','1933-05-15','Traditional Chinese Herbalist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 21,'Minerva','Todd','minerva.todd@kulmenim.ad','(763) 948-4815','1949-10-16','Electronic Drafter','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 22,'Bobby','Pearson','bobby.pearson@ib.kg','(238) 240-2561','2014-03-10','Vault Teller','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 23,'Larry','Ciappi','larry.ciappi@ba.lk','(410) 257-1723','1995-03-26','Fire Sprinkler Installer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 24,'Ronnie','Salucci','ronnie.salucci@tohhij.lv','(566) 726-3346','1973-09-27','Brewery Pumper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 25,'Walter','Grossi','walter.grossi@tuvo.sa','(416) 906-7221','1986-11-15','Kitchen Chef','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 26,'Frances','Koopmans','frances.koopmans@foga.tw','(611) 712-1562','1966-01-06','Medical Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 27,'Frances','Fujimoto','frances.fujimoto@uswuzzub.jp','(919) 887-8542','1935-06-12','Auto Tire Worker','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 28,'Olivia','Vidal','olivia.vidal@hivwerip.vc','(982) 684-7650','1932-09-19','Semi-Truck Driver','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 29,'Edna','Henry','edna.henry@gugusu.rw','(811) 931-8202','1946-08-03','Command And Control','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 30,'Lydia','Brun','lydia.brun@zedekak.md','(927) 400-3928','1928-09-15','Drywall Hanger','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 31,'Jay','Blake','jay.blake@ral.mk','(365) 345-1498','2008-10-03','Real Property Evaluator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 32,'Isabel','Serafini','isabel.serafini@turuhu.bh','(656) 968-9869','1972-10-11','Human Performance Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 33,'Rebecca','Carter','rebecca.carter@omjo.et','(739) 612-6585','1958-04-30','V/Stol Landing Signal Officer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 34,'Maurice','Fabbrini','maurice.fabbrini@rig.bh','(485) 521-2687','1992-03-05','Air Control/Anti-Air Warfare Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 35,'Ollie','Turnbull','ollie.turnbull@sicewap.org','(835) 620-3330','1943-10-31','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 36,'Jerry','Hopkins','jerry.hopkins@fo.mh','(211) 851-5960','2013-11-24','Child Protective Services Social Worker','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 37,'Nora','Lyons','nora.lyons@gegijap.na','(811) 311-5257','1944-09-07','Lens Grinder and Polisher','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 38,'Anne','Weiß','anne.weiß@kuvesa.pe','(843) 836-3759','1940-03-26','Civil Engineering Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 39,'Louise','Gauthier','louise.gauthier@lapahu.mt','(913) 235-1856','1929-07-06','Mobile Home Servicer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 40,'Lloyd','Fani','lloyd.fani@zev.ru','(467) 487-7239','1991-06-10','Floor Refinisher','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 41,'Maud','Dunn','maud.dunn@nabeaga.ni','(724) 340-3634','1954-09-01','Senior Sales Associate','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 42,'Henry','Gigli','henry.gigli@kaot.ps','(413) 229-8428','1987-11-04','Tile Designer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 43,'Virgie','Werner','virgie.werner@tawuctuj.cf','(886) 292-9749','1940-12-13','Econometrics Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 44,'Gregory','Cozzi','gregory.cozzi@eh.ru','(418) 472-1239','1993-10-06','Basketball Player','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 45,'Lucinda','Gil','lucinda.gil@fajjusuz.kr','(961) 233-3461','1933-09-27','Indirect Fire Infantryman','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 46,'Gertrude','Verbeek','gertrude.verbeek@pave.cc','(605) 226-4037','1963-10-11','Licensed Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 47,'Mattie','Graham','mattie.graham@ispaviw.gt','(719) 765-1705','1956-08-08','Antisubmarine Warfare Intelligence Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 48,'Bryan','Shaw','bryan.shaw@ha.ee','(232) 228-5539','2018-04-04','Research Assistant','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 49,'Essie','Adams','essie.adams@iliat.cw','(768) 554-8377','1957-10-14','Cigar Roller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 50,'Gary','Osborne','gary.osborne@do.ga','(311) 731-7079','2008-08-02','Customer Support Representative','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 51,'Richard','Silva','richard.silva@wi.lc','(207) 554-6244','2014-03-14','Programmer','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 52,'Dustin','Pestelli','dustin.pestelli@iwage.la','(558) 913-2855','1977-07-18','Global Engineering Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 53,'Henrietta','Hilton','henrietta.hilton@joopoju.pn','(832) 759-6654','1943-05-12','Telegraph and Teletype Operator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 54,'Francisco','Giordano','francisco.giordano@gojawu.tn','(482) 736-8079','1987-10-19','Hairpiece Stylist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 55,'Cynthia','Sardi','cynthia.sardi@afigoh.mm','(677) 345-2680','1973-04-08','Tobacco Buyer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 56,'Lula','Testi','lula.testi@benom.tj','(610) 374-7581','1971-02-03','Marine Steamfitter','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 57,'Bess','Lucas','bess.lucas@jevakbe.cd','(982) 583-8067','1928-07-14','Attending Anesthesiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 58,'Linnie','Driessen','linnie.driessen@darhow.tr','(680) 266-3167','1967-04-14','Certified Indoor Environmentalist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 59,'Eva','Tesi','eva.tesi@dupid.cf','(611) 955-4652','1971-02-24','Land Management Forester','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 60,'Augusta','Sakai','augusta.sakai@comouc.ee','(940) 714-8088','1935-12-02','Digital Proofing and Platemaker','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 61,'Mathilda','Schwarz','mathilda.schwarz@igunisi.ao','(868) 481-5125','1941-03-27','Public Health Veterinarian','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 62,'Joe','Riley','joe.riley@pe.vu','(225) 395-2772','2016-09-04','Statement Processor','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 63,'Leon','McGee','leon.mcgee@puk.se','(365) 837-6888','2010-06-21','Computer Applications Developer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 64,'Florence','Viviani','florence.viviani@vegub.no','(606) 352-8734','1969-04-13','African History Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 65,'Lee','Miceli','lee.miceli@rucwi.pf','(555) 800-7339','1981-07-17','Gastroenterology Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 66,'Celia','Sodi','celia.sodi@agijit.iq','(657) 357-3671','1972-05-09','Laboratory Animal Caretaker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 67,'Aaron','Misuri','aaron.misuri@loolu.lu','(523) 789-5485','1981-04-10','Water Pump Installer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 68,'Fanny','Parkinson','fanny.parkinson@tupwovali.cw','(766) 966-7387','1949-01-20','Orthopedic Cast Specialist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 69,'Phoebe','Vitale','phoebe.vitale@hidge.fo','(672) 613-2954','1969-05-23','Budget Coordinator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 70,'Edith','Brennan','edith.brennan@liowci.ir','(803) 549-9387','1947-11-02','Railroad Engineer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 71,'Jeremy','Marilli','jeremy.marilli@vesa.pf','(526) 435-1819','1983-05-07','Chief Projectionist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 72,'Kathryn','Huet','kathryn.huet@wupikdoh.by','(937) 855-5936','1926-10-24','Telecasting Engineer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 73,'Lelia','Matsuo','lelia.matsuo@dajsiphaj.az','(960) 335-6192','1934-11-04','Drama Therapist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 74,'Virginia','Woods','virginia.woods@soofpe.ht','(735) 809-2611','1954-08-12','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 75,'Sally','Aoki','sally.aoki@aruzusjas.tc','(857) 797-7918','1936-10-13','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 76,'Isabelle','de Ridder','isabelle.deridder@ufeco.in','(659) 331-1543','1962-07-30','Leisure Studies Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 77,'Rosie','Murphy','rosie.murphy@uneehi.id','(759) 639-8597','1958-01-30','Air Conditioning Service Technician','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 78,'Lou','Meyer','lou.meyer@hahinaba.gm','(942) 352-4854','1928-10-25','Business Unit Manager','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 79,'Rodney','Love','rodney.love@zun.ph','(247) 867-8287','2012-02-19','Job Estimator','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 80,'Kenneth','Bianchini','kenneth.bianchini@jo.ws','(302) 793-9936','2001-02-10','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 81,'Essie','Dietrich','essie.dietrich@goltuefo.mn','(861) 740-6628','1938-10-13','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 82,'Leila','Simon','leila.simon@lupuwuzo.gw','(953) 866-9992','1930-07-10','Signals Intelligence/Electronic Warfare Chief','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 83,'Eva','Pierre','eva.pierre@reduzris.ee','(915) 491-8384','1927-07-22','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 84,'Landon','Moretti','landon.moretti@pubsav.sk','(584) 909-6235','1980-10-24','Wildlife Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 85,'Mittie','Sardi','mittie.sardi@lullip.nf','(673) 849-4256','1973-04-03','Food Chemist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 86,'Corey','McDaniel','corey.mcdaniel@aba.tc','(268) 208-9643','2012-06-07','Advanced Foreign Counterintelligence Specialist (Afcs)','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 87,'Hester','Stein','hester.stein@kettujwo.eu','(873) 489-6641','1939-03-31','Forest Fire Officer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 88,'Danny','Lowe','danny.lowe@ju.sd','(243) 974-5539','2013-07-13','Catalogue Illustrator','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 89,'Lillie','Winter','lillie.winter@vioburez.vi','(816) 699-1291','1945-06-07','Knife Grinder','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 90,'Brandon','Borchi','brandon.borchi@ig.al','(319) 401-1090','2000-03-29','Neuropsychiatrist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 91,'Isaac','Bernardi','isaac.bernardi@omu.bj','(359) 691-6408','2001-09-09','Bottle Packer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 92,'Clyde','Crawford','clyde.crawford@luw.dz','(273) 892-4646','2018-09-12','Special Education Kindergarten Teacher','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 93,'Paul','Sherman','paul.sherman@pi.cf','(304) 610-2881','2008-02-19','Commercial Art Instructor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 94,'Craig','Russell','craig.russell@zu.nz','(237) 969-2900','2019-12-17','Ferryboat Captain','Supervisor',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 95,'John','Sutton','john.sutton@ag.ee','(207) 424-6468','2013-02-27','School Social Worker','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 96,'Francisco','Formigli','francisco.formigli@fopav.tn','(481) 661-8179','1990-02-11','Joint Terminal Attack Controller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 97,'Gary','Baker','gary.baker@ji.cf','(212) 510-3444','2022-03-03','VP Sales','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 98,'Earl','Giovannoni','earl.giovannoni@lojet.ge','(433) 862-3076','1987-07-12','Auto Service Station Attendant','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 99,'Helen','Zanieri','helen.zanieri@ukve.tn','(619) 506-4452','1968-11-23','Healthcare Social Worker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 100,'Agnes','Toccafondi','agnes.toccafondi@viipo.ae','(616) 688-6883','1970-12-13','Comedian','External',false)
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 1,'Eula','Cheat Spread','jigrormo','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 2,'Barry','petits Pains Grillés au froment','zun','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 3,'Eugenia','Pain croustillant complet riche en fibres','capfad','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 4,'Alejandro','Chocapic','dec','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 5,'Cora','Riz long parfumé naturellement','bivo','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 6,'Marguerite','Mini mozzarella','judbilo','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 7,'Mildred','Cono helado','joraf','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 8,'Gene','Pâté de légumes','kem','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 9,'Lettie','bridelice crème légère','odeter','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 10,'Mabel','6 oeufs plein air bio','lisohuje','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 11,'Jordan','Graines de Chia','duod','5')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 12,'Marie','4 quesos','nowufpus','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 13,'Rose','Miel de fleurs sauvages','kagu','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 14,'Garrett','Tropicaa pure premium orange avec pulpe','fef','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 15,'Barbara','Pur Jus Pomme de Provence','derwogi','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 16,'Jean','Delikatess Kochhinterschinken','wehovuce','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 17,'Jack','Levure du boulanger Briochin','zamum','5')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 18,'Pearl','Zumo de naranja','dunebuh','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 19,'Belle','Sauce bolognaise','repiwid','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 20,'Olive','le foie gras de canard entier du sud ouest','razuppa','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 21,'Minerva','Activia So Délicat Pointe de Citron Vert','kulmenim','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 22,'Bobby','Sås senap & dill','ib','1')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 23,'Larry','Sandwich camembert beurre','ba','3')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 24,'Ronnie','Nutabreizh','tohhij','5')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 25,'Walter','sirop de Cannes canadou citron','tuvo','4')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 26,'Frances','wraps nature','foga','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 27,'Frances','Woodhaven','uswuzzub','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 28,'Olivia','Daddy sirop d''agave bio','hivwerip','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 29,'Edna','Cordon bleu','gugusu','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 30,'Lydia','cal c tose','zedekak','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 31,'Jay','Kiwi-limoen aloe vera','ral','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 32,'Isabel','Fourre cacao','turuhu','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 33,'Rebecca','Cider Paron (perencider) 4,5% Blik','omjo','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 34,'Maurice','Colorant alimentaire rouge groseille','rig','4')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 35,'Ollie','Melange de fruits secs','sicewap','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 36,'Jerry','Hamburguesa pollo rulo/cebolla','fo','1')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 37,'Nora','Micorwave Popcorn Salted','gegijap','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 38,'Anne','kerrygold pure Irish butter','kuvesa','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 39,'Louise','Cebolla roja','lapahu','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 40,'Lloyd','Sea salt caramel','zev','4')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 41,'Maud','Pain allongé 9 grains','nabeaga','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 42,'Henry','Mirabelle de Lorraine','kaot','4')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 43,'Virgie','Regal','tawuctuj','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 44,'Gregory','tartinades de thon aubergones et olives','eh','3')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 45,'Lucinda','Spaghetti biologiqie','fajjusuz','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 46,'Gertrude','Fried onions','pave','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 47,'Mattie','Corn Kernels','ispaviw','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 48,'Bryan','Spaghetti al pesto genovés','ha','1')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 49,'Essie','Skittles','iliat','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 50,'Gary','chili beef burger','do','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 51,'Richard','Clipsy','wi','1')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 52,'Dustin','Pâte à tartiner','iwage','5')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 53,'Henrietta','cake aux fruits','joopoju','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 54,'Francisco','Roasted Monkey Nuts','gojawu','4')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 55,'Cynthia','Kebab poluet dinde','afigoh','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 56,'Lula','Pancakes','benom','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 57,'Bess','Lachs Kartoffelauflauf','jevakbe','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 58,'Linnie','Biscotte Muesli et Pépites d''Abricot','darhow','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 59,'Eva','Pate a sucre','dupid','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 60,'Augusta','Pago fraise','comouc','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 61,'Mathilda','Sel de table','igunisi','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 62,'Joe','Funny crisp','pe','1')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 63,'Leon','Arraw','puk','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 64,'Florence','mayonnaise','vegub','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 65,'Lee','Le Gusto Basilikum gartenfrisch gefriergetrocknet','rucwi','5')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 66,'Celia','Corn flakes','agijit','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 67,'Aaron','Mont blanc saveur vanille','loolu','5')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 68,'Fanny','BioLassi','tupwovali','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 69,'Phoebe','Pain de campagne','hidge','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 70,'Edith','Huile de colza aromatise thym','liowci','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 71,'Jeremy','Compota de naranja y genjibre','vesa','5')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 72,'Kathryn','Nutrasart','wupikdoh','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 73,'Lelia','Cordons bleus de volaille','dajsiphaj','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 74,'Virginia','Huvudroll','soofpe','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 75,'Sally','Cappuccino','aruzusjas','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 76,'Isabelle','Frische Vollmilch','ufeco','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 77,'Rosie','pâte à tartiner','uneehi','7')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 78,'Lou','Sucette S piral Colours Goût Tutti Frutti','hahinaba','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 79,'Rodney','pruneau d''Agen','zun','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 80,'Kenneth','Tortilla chips fajitas','jo','3')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 81,'Essie','Barre chocolat noir - 85% cacao','goltuefo','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 82,'Leila','Emmental français rapé','lupuwuzo','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 83,'Eva','Modern Bakery Protein Slice Bread','reduzris','10')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 84,'Landon','Chocolat en poudre','pubsav','5')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 85,'Mittie','Velouté de carottes','lullip','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 86,'Corey','Préparation pour vin chaud à base de cassonade et d''épices','aba','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 87,'Hester','César MORONI chorizo','kettujwo','9')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 88,'Danny','Velouté de potiron et graines de courge bio','ju','1')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 89,'Lillie','Pain au levin','vioburez','8')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 90,'Brandon','Longaniza blanca casera','ig','3')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 91,'Isaac','sable tres cafe','omu','3')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 92,'Clyde','L''Oustal des chips','luw','1')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 93,'Paul','Jamón de Teruel DOP','pi','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 94,'Craig','Assaisonnement Basque','zu','1')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 95,'John','Cacau Maigre','ag','2')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 96,'Francisco','Ravioli 6 légumes','fopav','4')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 97,'Gary','Aperol','ji','1')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 98,'Earl','Almondmilk Creamer with Coconut','lojet','4')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 99,'Helen','Godis Chokladran','ukve','6')
insert into producto(version, id,nombre,descripcion,precio,cantidad) values (1, 100,'Agnes','Nouilles vegetables','viipo','6')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 1,'Eula','Cheat Spread','Ohio','Philippines')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 2,'Barry','petits Pains Grillés au froment','Colorado','Bhutan')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 3,'Eugenia','Pain croustillant complet riche en fibres','Missouri','Liechtenstein')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 4,'Alejandro','Chocapic','Colorado','Bhutan')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 5,'Cora','Riz long parfumé naturellement','Montana','Macedonia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 6,'Marguerite','Mini mozzarella','Utah','Syria')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 7,'Mildred','Cono helado','New Hampshire','Mexico')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 8,'Gene','Pâté de légumes','Delaware','Burkina Faso')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 9,'Lettie','bridelice crème légère','North Carolina','Norfolk Island')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 10,'Mabel','6 oeufs plein air bio','Rhode Island','Slovenia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 11,'Jordan','Graines de Chia','Massachusetts','Iran')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 12,'Marie','4 quesos','South Dakota','Sri Lanka')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 13,'Rose','Miel de fleurs sauvages','North Carolina','Norway')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 14,'Garrett','Tropicaa pure premium orange avec pulpe','Delaware','Cameroon')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 15,'Barbara','Pur Jus Pomme de Provence','West Virginia','Ukraine')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 16,'Jean','Delikatess Kochhinterschinken','Pennsylvania','Saudi Arabia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 17,'Jack','Levure du boulanger Briochin','Missouri','Lebanon')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 18,'Pearl','Zumo de naranja','Pennsylvania','Saudi Arabia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 19,'Belle','Sauce bolognaise','Virginia','Turkmenistan')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 20,'Olive','le foie gras de canard entier du sud ouest','Virginia','Trinidad & Tobago')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 21,'Minerva','Activia So Délicat Pointe de Citron Vert','Oregon','Samoa')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 22,'Bobby','Sås senap & dill','California','Belize')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 23,'Larry','Sandwich camembert beurre','Indiana','Equatorial Guinea')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 24,'Ronnie','Nutabreizh','Missouri','Liberia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 25,'Walter','sirop de Cannes canadou citron','Louisiana','Guadeloupe')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 26,'Frances','wraps nature','New Hampshire','Micronesia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 27,'Frances','Woodhaven','Utah','Tanzania')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 28,'Olivia','Daddy sirop d''agave bio','Virginia','Tristan da Cunha')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 29,'Edna','Cordon bleu','Rhode Island','Singapore')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 30,'Lydia','cal c tose','West Virginia','United Kingdom')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 31,'Jay','Kiwi-limoen aloe vera','Delaware','Cambodia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 32,'Isabel','Fourre cacao','Missouri','Liechtenstein')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 33,'Rebecca','Cider Paron (perencider) 4,5% Blik','North Carolina','North Korea')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 34,'Maurice','Colorant alimentaire rouge groseille','Iowa','France')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 35,'Ollie','Melange de fruits secs','South Carolina','South Georgia & South Sandwich Islands')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 36,'Jerry','Hamburguesa pollo rulo/cebolla','California','Benin')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 37,'Nora','Micorwave Popcorn Salted','South Carolina','Somalia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 38,'Anne','kerrygold pure Irish butter','Tennessee','St. Martin')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 39,'Louise','Cebolla roja','Washington','Uganda')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 40,'Lloyd','Sea salt caramel','Kansas','French Polynesia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 41,'Maud','Pain allongé 9 grains','Ohio','Paraguay')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 42,'Henry','Mirabelle de Lorraine','Louisiana','Greenland')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 43,'Virgie','Regal','Tennessee','St. Lucia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 44,'Gregory','tartinades de thon aubergones et olives','Iowa','Falkland Islands')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 45,'Lucinda','Spaghetti biologiqie','Vermont','Tonga')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 46,'Gertrude','Fried onions','New Jersey','Morocco')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 47,'Mattie','Corn Kernels','North Dakota','Pakistan')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 48,'Bryan','Spaghetti al pesto genovés','Arizona','Ascension Island')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 49,'Essie','Skittles','North Carolina','Northern Mariana Islands')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 50,'Gary','chili beef burger','Delaware','Cambodia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 51,'Richard','Clipsy','California','Belize')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 52,'Dustin','Pâte à tartiner','Minnesota','Kazakhstan')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 53,'Henrietta','cake aux fruits','South Carolina','South Korea')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 54,'Francisco','Roasted Monkey Nuts','Louisiana','Greenland')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 55,'Cynthia','Kebab poluet dinde','Missouri','Libya')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 56,'Lula','Pancakes','Montana','Macedonia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 57,'Bess','Lachs Kartoffelauflauf','West Virginia','United Kingdom')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 58,'Linnie','Biscotte Muesli et Pépites d''Abricot','Nevada','Mauritius')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 59,'Eva','Pate a sucre','Montana','Macedonia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 60,'Augusta','Pago fraise','Utah','Tajikistan')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 61,'Mathilda','Sel de table','South Dakota','St. Kitts & Nevis')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 62,'Joe','Funny crisp','Arkansas','Bahamas')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 63,'Leon','Arraw','Connecticut','Brunei')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 64,'Florence','mayonnaise','Nebraska','Mali')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 65,'Lee','Le Gusto Basilikum gartenfrisch gefriergetrocknet','Massachusetts','Iran')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 66,'Celia','Corn flakes','Montana','Lithuania')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 67,'Aaron','Mont blanc saveur vanille','Massachusetts','Iran')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 68,'Fanny','BioLassi','Pennsylvania','São Tomé and Príncipe')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 69,'Phoebe','Pain de campagne','Nebraska','Mali')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 70,'Edith','Huile de colza aromatise thym','Pennsylvania','Serbia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 71,'Jeremy','Compota de naranja y genjibre','Maryland','Hong Kong SAR China')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 72,'Kathryn','Nutrasart','Wisconsin','Vanuatu')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 73,'Lelia','Cordons bleus de volaille','Vermont','Timor-Leste')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 74,'Virginia','Huvudroll','Ohio','Paraguay')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 75,'Sally','Cappuccino','Utah','Syria')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 76,'Isabelle','Frische Vollmilch','New Mexico','Namibia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 77,'Rosie','pâte à tartiner','North Carolina','North Korea')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 78,'Lou','Sucette S piral Colours Goût Tutti Frutti','West Virginia','United Arab Emirates')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 79,'Rodney','pruneau d''Agen','Colorado','Bosnia & Herzegovina')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 80,'Kenneth','Tortilla chips fajitas','Hawaii','Costa Rica')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 81,'Essie','Barre chocolat noir - 85% cacao','Texas','Suriname')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 82,'Leila','Emmental français rapé','Washington','U.S. Outlying Islands')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 83,'Eva','Modern Bakery Protein Slice Bread','West Virginia','Uruguay')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 84,'Landon','Chocolat en poudre','Massachusetts','Ireland')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 85,'Mittie','Velouté de carottes','Missouri','Libya')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 86,'Corey','Préparation pour vin chaud à base de cassonade et d''épices','Colorado','Bosnia & Herzegovina')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 87,'Hester','César MORONI chorizo','Texas','Sudan')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 88,'Danny','Velouté de potiron et graines de courge bio','Colorado','Bermuda')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 89,'Lillie','Pain au levin','Rhode Island','Slovenia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 90,'Brandon','Longaniza blanca casera','Hawaii','Croatia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 91,'Isaac','sable tres cafe','Hawaii','Cook Islands')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 92,'Clyde','L''Oustal des chips','Arizona','Aruba')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 93,'Paul','Jamón de Teruel DOP','Delaware','Cameroon')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 94,'Craig','Assaisonnement Basque','Alaska','Antigua & Barbuda')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 95,'John','Cacau Maigre','Colorado','Bhutan')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 96,'Francisco','Ravioli 6 légumes','Kentucky','Gambia')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 97,'Gary','Aperol','Alabama','Algeria')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 98,'Earl','Almondmilk Creamer with Coconut','Louisiana','Grenada')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 99,'Helen','Godis Chokladran','Nebraska','Malta')
insert into aduana(version, id,nombre,direccion,ciudad,pais) values (1, 100,'Agnes','Nouilles vegetables','Montana','Madagascar')
